# Generated by Django 2.1.3 on 2018-11-14 05:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='pickup',
            field=models.CharField(default='Medellin, parque del Poblado', max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='doors',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)]),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(default='Mecanica', max_length=20),
        ),
    ]
