# Generated by Django 2.1.3 on 2018-11-20 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
