# Generated by Django 2.1.3 on 2018-11-14 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0002_auto_20181114_0504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='pickup',
            field=models.CharField(default='Medellin, Aeropuerto Olaya Herrera', max_length=100),
        ),
    ]
