# Generated by Django 2.1.3 on 2018-11-30 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0002_auto_20181130_0738'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarRent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fromDate', models.DateField()),
                ('toDate', models.DateField()),
                ('token', models.CharField(default='defaultToke', max_length=100)),
                ('uidUser', models.CharField(default='defaultUidUser', max_length=100)),
                ('bookingDate', models.DateField()),
                ('pickup', models.CharField(default='Aeropuerto', max_length=100)),
                ('pickupDate', models.DateField()),
                ('deliverPlace', models.CharField(default='Aeropuerto', max_length=100)),
                ('deliverDate', models.DateField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detail.Car')),
                ('rental', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='detail.CarRental')),
            ],
        ),
    ]
