# Generated by Django 2.1.3 on 2018-11-20 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0002_auto_20181120_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarRental',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('_id', models.IntegerField(default=967543461)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='car',
            name='rental',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detail.CarRental'),
        ),
    ]
