# Generated by Django 2.1.3 on 2018-11-30 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0003_carrent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrent',
            name='fromDate',
        ),
        migrations.RemoveField(
            model_name='carrent',
            name='toDate',
        ),
    ]
