# Generated by Django 2.1.3 on 2018-11-20 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0003_auto_20181120_2035'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rental',
        ),
    ]
