# Generated by Django 2.1.3 on 2018-11-30 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0004_delete_rental'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='bookingDate',
            field=models.DateField(default='2018-11-30'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='deliverDate',
            field=models.DateField(default='2018-11-30'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='deliverPlace',
            field=models.CharField(default='Aeropuerto', max_length=100),
        ),
        migrations.AddField(
            model_name='reservation',
            name='pickup',
            field=models.CharField(default='Aeropuerto', max_length=100),
        ),
        migrations.AddField(
            model_name='reservation',
            name='pickupDate',
            field=models.DateField(default='2018-11-30'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='rental',
            field=models.ForeignKey(default=(), on_delete=django.db.models.deletion.CASCADE, to='detail.CarRental'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='token',
            field=models.CharField(default='---', max_length=100),
        ),
        migrations.AddField(
            model_name='reservation',
            name='uidUser',
            field=models.CharField(default='---', max_length=100),
        ),
    ]
