# Generated by Django 2.1.3 on 2018-11-30 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0004_auto_20181130_0750'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
