# Generated by Django 2.1.3 on 2018-11-15 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0004_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='pickup',
            field=models.CharField(default='Aeropuerto', max_length=100),
        ),
    ]
