# Generated by Django 2.1.3 on 2018-11-15 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0004_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='fromDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='toDate',
            field=models.DateField(),
        ),
    ]
