# Generated by Django 2.1.3 on 2018-11-30 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0007_auto_20181130_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='bookingDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='deliverDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='pickupDate',
            field=models.DateField(),
        ),
    ]
