# Generated by Django 2.1.3 on 2018-11-30 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0009_auto_20181130_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='rental',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='detail.CarRental'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='token',
            field=models.CharField(default='defaultToke', max_length=100),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='uidUser',
            field=models.CharField(default='defaultUidUser', max_length=100),
        ),
    ]
